### ISSUE TITLE
Should Branches property to be required in Parallel step schema?

### ISSUE THREAD

**Issue by wmakeev** [airware/asl-validator#1]
https://github.com/airware/asl-validator/blob/0926c2b4236b7f91a9879040b6ec032d0b0e569b/src/schemas/parallel.json#L25

https://runkit.com/wmakeev/aslvalidator-parallel

**Comment by ChristopheBougere** [comment]
Hi @wmakeev,
You are right, [should be invalid](http://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-parallel-state.html). This package is still in early stage, I will fix this.
I would like to add a bunch of invalid wrong definitions in [test files](https://github.com/airware/asl-validator/tree/master/src/__tests__/definitions), this looks like a good start!
Thanks

**Comment by ChristopheBougere** [comment]
Fixed in 1.0.2
Thanks for the feedback, please let us know if you find some new issues
