### ISSUE TITLE
parallel state validator throws error if it has "Retry" field

### ISSUE THREAD

**Issue by ZQi** [airware/asl-validator#27]
Could you please add "Retry" field in parallel schema? Thanks!

**Comment by ChristopheBougere** [comment]
Can you have a look to #28 ?

**Comment by ZQi** [comment]
Looks awesome! Thanks a lot! Could I know when this will be merged? Thanks!

**Comment by ChristopheBougere** [comment]
Merged and published (version 1.1.1)
