### ISSUE TITLE
Is there an overall schema (for use with editor autocomplete)?

### ISSUE THREAD

**Issue by studds** [airware/asl-validator#48]
I had a search around, and I couldn't find an overall schema for ASL, in order to get editor autocomplete working in vscode.

I've put all the schemas from this repository together in a single schema here: https://gist.githubusercontent.com/studds/b9dbba056eaaaf42dfe70c191c12d848/raw/38a37cd9b3c1f48ad622df11261c314d2bf282da/aws-step-function.json

It seems to be working fine, am I reinventing the wheel?

**Comment by ChristopheBougere** [comment]
Hi @studds,

> Is there an overall schema

There isn't. If needed, we could probably add a compiling step that would aggregate all schema pieces in a single file, in a pre-push hook for instance.

> Am I reinventing the wheel?

Maybe 😄 [AWS Toolkit for VS now supports StepFunctions](https://aws.amazon.com/blogs/compute/aws-step-functions-support-in-visual-studio-code/), and should already fit your needs.

Let me know if that's enough

**Comment by studds** [comment]
Yep, more than enough. Thankfully I didn't spend too much time on this!!
